# ------------------------------日志配置--------------------------------------
logging:
  config: classpath:log4j2-dev.yml
---
# ------------------------------数据库配置------------------------------------
spring:
  datasource:
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 连接池初始化连接数
    initialSize: 5
    # 连接池最小连接数
    minIdle: 5
    # 连接池最大连接数
    maxActive: 20
    # 获取连接等待超时的时间，单位是毫秒
    maxWait: 60000
    # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: ture
    maxPoolPreparedStatementPerConnectionSize: 20
    # 监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
---
# ------------------------------Mybatis配置----------------------------------
mybatis:
  type-aliases-package: com.fesco.saashr.web.model
---
# ------------------------------Redis配置-------------------------------------
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    host: 192.168.153.128
    port: 6379
    password: 123qwe
---
# ------------------------------Thymeleaf配置--------------------------------
spring:
  thymeleaf:
    cache: false
---